repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: dotnet-tool-restore
        name: Install .NET tools
        entry: dotnet tool restore
        language: system
        always_run: true
        pass_filenames: false
        stages:
          - pre-commit
          - pre-push
          - post-checkout
          - post-rewrite
      - id: csharpier
        name: Run CSharpier on C# files
        entry: dotnet tool run csharpier check
        language: system
        types:
          - c#
