<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>1.0.0-alpha.1</Version>
    <Authors>Simon Gurcke</Authors>
    <Company>Apitally</Company>
    <Description>SDK for Apitally, a simple API monitoring and analytics tool for REST APIs built with ASP.NET Core.</Description>
    <PackageProjectUrl>https://apitally.io</PackageProjectUrl>
    <RepositoryUrl>https://github.com/apitally/apitally-dotnet</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <PackageTags>api;monitoring;analytics;aspnetcore;opentelemetry</PackageTags>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
    <None Include="icon.png" Pack="true" PackagePath="/" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenTelemetry" Version="1.19.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.19.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.19.0" />
    <PackageReference Include="Google.Protobuf" Version="3.33.5" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf
      Include="Protos/opentelemetry/proto/**/*.proto"
      ProtoRoot="Protos"
      GrpcServices="None"
      Access="Internal"
    />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Apitally.Tests" />
  </ItemGroup>
</Project>
